FROM php:7.4.12-apache
LABEL maintainer="mobilemailer@web.de"

RUN apt-get update

#RUN apt-get install -y certbot
#RUN openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048

#RUN apt-get install -y libmagickwand-dev --no-install-recommends && rm -rf /var/lib/apt/lists/*
#RUN printf "\n" | pecl install imagick
#RUN docker-php-ext-enable imagick
#RUN pear channel-discover pear.horde.org

